# Config for the main half

# On some operating systems, such as PopOS! 22.04 or 24.04, the Bluetooth connection might not work properly,
#    so this flag fixes the problem, but makes it so that during pairing you have to enter the code on the keyboard.
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
